<template>
  <div class="loadingio-spinner-blocks-39b6x2060f6"><div class="ldio-anzbxjol8lf">
  <div style='left:13.02px;top:13.02px;animation-delay:0s'></div><div style='left:37.82px;top:13.02px;animation-delay:0.08333333333333333s'></div><div style='left:62.62px;top:13.02px;animation-delay:0.16666666666666666s'></div><div style='left:87.42px;top:13.02px;animation-delay:0.25s'></div><div style='left:13.02px;top:37.82px;animation-delay:0.9166666666666666s'></div><div style='left:87.42px;top:37.82px;animation-delay:0.3333333333333333s'></div><div style='left:13.02px;top:62.62px;animation-delay:0.8333333333333334s'></div><div style='left:87.42px;top:62.62px;animation-delay:0.4166666666666667s'></div><div style='left:13.02px;top:87.42px;animation-delay:0.75s'></div><div style='left:37.82px;top:87.42px;animation-delay:0.6666666666666666s'></div><div style='left:62.62px;top:87.42px;animation-delay:0.5833333333333334s'></div><div style='left:87.42px;top:87.42px;animation-delay:0.5s'></div>
  </div></div>
</template>


  <style>
  @keyframes ldio-anzbxjol8lf {
    0% { background: #44de28 }
    8.333333333333334% { background: #44de28 }
    8.416666666666666% { background: #006aff }
    100% { background: #006aff }
  }
  .ldio-anzbxjol8lf div {
    position: absolute;
    width: 23.56px;
    height: 23.56px;
    background: #006aff;
    animation: ldio-anzbxjol8lf 1s linear infinite;
  }
  .loadingio-spinner-blocks-39b6x2060f6 {
    width: 124px;
    height: 124px;
    display: inline-block;
    overflow: hidden;
    background: #f1f2f3;
  }
  .ldio-anzbxjol8lf {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
  }
  .ldio-anzbxjol8lf div { box-sizing: content-box; }
  /* generated by https://loading.io/ */
  </style>